apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: logging-cluster
  region: eu-west-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "scheduler", "api", "controllerManager"]
#    enableTypes: ["*"]