apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-west-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
        efs: true
        albIngress: true
        cloudWatch: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 50
    labels: { role: workers }
    privateNetworking: true
    ssh:
      publicKeyPath: ~/.ssh/eksctl_pub
    availabilityZones: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]

  - name: ng-2
    instanceType: m5.large
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
        efs: true
        albIngress: true
        cloudWatch: true
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 100
    labels: { role: builders }
    privateNetworking: true
    ssh:
      publicKeyPath: ~/.ssh/eksctl_pub
    availabilityZones: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]

  - name: ng-3
    minSize: 1
    maxSize: 2
    labels: { role: ephemeral-workers}
    volumeSize: 50
    ssh:
      publicKeyPath: ~/.ssh/eksctl_pub
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
        efs: true
        albIngress: true
        cloudWatch: true
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    
